Controllers/BtradeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kudvenkatcorewebapp.DBContext;
using Kudvenkatcorewebapp.Models.Trade;
using Kudvenkatcorewebapp.Repository.Trade;
using Kudvenkatcorewebapp.ViewModels.Trade;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Kudvenkatcorewebapp.Controllers
{
    [Authorize(Roles ="Admin")]
    public class BtradeController : Controller
    {
        private readonly IBrokerRepository _brokerRepository;
        private readonly ITradeshare _tradeinformation;
        private readonly AppDbContext appDbContext;
        //SharetradeRepository sr=new SharetradeRepository();

        public BtradeController(IBrokerRepository brokerRepository, ITradeshare tradeinformation,AppDbContext appDbContext)
        {
            this._brokerRepository = brokerRepository;
            this._tradeinformation = tradeinformation;
            this.appDbContext = appDbContext;
        }
        public async Task<IActionResult> Index()
        {
            var brokerlist =await _brokerRepository.GetAllBrokerListusingIenumerable();
            return View(brokerlist);
        }
        
        public async Task<IActionResult> BrokerDropdownList()
        {
            //ViewBag.brokerlist = new SelectList(await _brokerRepository.GetAllBrokerListusingIenumerable(), "ID", "BrokerName");
            string name = "";
            IEnumerable<Tradeinformation> brokerlist = await _tradeinformation.GetTradeInformationList(name);
            ////return View(__StocksnformationView, brokerlist);
            //return PartialView("_StocksnformationView", brokerlist);
            return View(brokerlist);
        }

        public async Task<IActionResult> GetAllStocks()
        {
            string name = "";
            IEnumerable<Tradeinformation> sharelist = await _tradeinformation.GetTradeInformationList(name);
            return View(sharelist);
        }

        public async Task<IActionResult> GetAllStocksAjax()
        {
            int id = Convert.ToInt32(TempData["ID"]);
            ViewBag.message = id;
            string name = "";
            IEnumerable<Tradeinformation> sharelist = await _tradeinformation.GetTradeInformationList(name);
            return View(sharelist);
        }

        [HttpGet]
        public async Task<IActionResult> ShareCreate()
        {
            ViewBag.brokerlist = new SelectList(await _brokerRepository.GetAllBrokerListusingIenumerable(), "ID", "BrokerName");
            return View();
        }

        [HttpPost]
        public IActionResult ShareCreate(BrokerTradeViewModel model)
        {
            ExtraQuantityAddedinStocks exqs = new ExtraQuantityAddedinStocks();
            //double im = sr.TotalInvestedAmountinShares(model.tradeinformation.Stockbuykprice, model.tradeinformation.Stocktotalshares);
            model.tradeinformation.TotalInvestedAmount = 0;
           
            if (ModelState.IsValid)
            {
                Tradeinformation tradeinformation = new Tradeinformation
                {
                    brokerid = model.tradeinformation.brokerid,
                    Stockname = model.tradeinformation.Stockname,
                    Stockbuykprice = model.tradeinformation.Stockbuykprice,
                    Stocksellprice = model.tradeinformation.Stocksellprice,
                    Stocktotalshares = model.tradeinformation.Stocktotalshares,
                    TotalInvestedAmount = model.tradeinformation.TotalInvestedAmount,
                    Stockpurchaseddate = model.tradeinformation.Stockpurchaseddate,
                    Stockselldate = model.tradeinformation.Stockselldate,
                    Active = 1,
                };
                _tradeinformation.AddITradeinformation(tradeinformation);
                
                if (tradeinformation.Id > 0)
                {
                    int sngid = 1;

                    TempData["ID"] = sngid;

                    return RedirectToAction("GetAllStocksAjax");
                }
                return RedirectToAction("GetAllStocks");
            }
                //ViewBag.brokerlist = new SelectList(await _brokerRepository.GetAllBrokerListusingIenumerable(), "ID", "BrokerName");
                return View();
        }

        [HttpPost]
        public IActionResult DeleteShare(int id)
        {
            Tradeinformation tradeinformation = appDbContext.tradeinformations.Where(t => t.Id == id).FirstOrDefault();
            appDbContext.Entry(tradeinformation).State = EntityState.Deleted;
            appDbContext.SaveChanges();
            return Ok();
        }
        
        [HttpPost]
        public IActionResult ViewShare(int id)
        {
            Tradeinformation tradeinformation = appDbContext.tradeinformations.Where(t => t.Id == id).FirstOrDefault();
            return PartialView("_Detail", tradeinformation);
           
        }
    }
}

Views/Btrade/BrokerDropdownList.cshtml
@model  IEnumerable<BrokerTradeViewModel>


@{
    ViewData["Title"] = "BrokerDropdownList";
}

    <div class="expand-lg navbar-light bg-light m-1">
        <h1>BROKER DETAILS</h1>

        @*<div class="form-group">
            <label asp-for="BrokerName" class="control-label"></label>
            <select asp-for="BrokerName" class="form-control" asp-items=" ViewBag.brokerlist">
                <option value="">Please select City</option>
            </select>

        </div>*@

        @*<div class="form-group">
            <label asp-for="BrokerName" class="control-label"></label>
            <select asp-for="BrokerName" class="form-control" asp-items=" ViewBag.brokerlist">
                <option value="">Please select City</option>
            </select>
        </div>*@

        @foreach (var i in Model)
        {
            <partial name="_StocksnformationView" model="i" />
        }

    </div>



    <script>
        $(document).ready(function () {
            $("#hide").click(function () {
                $("p").hide();
            });
            $("#show").click(function () {
                $("p").show();
            });
        });
    </script>

Views/Btrade/GetAllStocks.cshtml
@model IEnumerable<Tradeinformation>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<p><a asp-action="ShareCreate" asp-controller="Btrade" class="btn btn-sm btn-success m-1">Create New Stock</a></p>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Stockname</th>
            <th>Stockbuykprice</th>
            <th>Stocksellprice</th>
            <th>Stocktotalshares</th>
            <th>Stock purchased date</th>
            <th>Stock sell date</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <td>@Html.DisplayFor(m => item.Stockname)</td>
            <td>@Html.DisplayFor(m => item.Stockbuykprice)</td>
            <td>@Html.DisplayFor(m => item.Stocksellprice)</td>
            <td>@Html.DisplayFor(m => item.Stocktotalshares)</td>
            <td>@Html.DisplayFor(m => item.Stockpurchaseddate)</td>
            <td>@Html.DisplayFor(m => item.Stockselldate)</td>
            <td>
                <div class="btn-group">
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-info">EDIT</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-info">DELETE</a>
                </div>
            </td>
        </tr>
        }
    </tbody>
</table>

Views/Btrade/GetAllStocksAjax.cshtml
@model IEnumerable<Tradeinformation>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@if (@ViewBag.message == 1)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Good!</strong> Successfully Inserted Your Data.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
<p><a asp-action="ShareCreate" asp-controller="Btrade" class="btn btn-sm btn-success m-1">Create New Stock</a></p>

<table class="table table-striped text-sm-center font-weight-bold mx-auto">
    <thead class="bg-info text-white">
        <tr>
            <th>SL NO</th>
            <th>ID</th>
            <th>Stockname</th>
            <th>Stockbuykprice</th>
            <th>Stocksellprice</th>
            <th>Stocktotalshares</th>
            <th>Stock purchased date</th>
            <th>Stock sell date</th>
            <th>Total Invested Amount</th>
            <th>Broker Name</th>
            <th>Actions</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Select((x, i) => new { data = x, Index = i }))
        {
            <tr id="TR_@item.data.Id">
                <td>
                    @( ((Int32)1) + item.Index )
                </td>
               
                <partial name="_Allstocinformation" model="@item.data" />
            </tr>
        }
    </tbody>

    <tfoot class="bg-info text-white">
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td>@Model.Sum(i => i.TotalInvestedAmount)</td>
            <td></td>
            <td></td>
        </tr>
    </tfoot>
</table>


@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script>
    function deleteItem(form) {
        var RemoveItem1 = $(form);
        RemoveItem1.closest("tr").remove();
    }

    function ShowDetailForm() {
        $("#DivDetailView").addClass("visible");
        $("#DivDetailView").removeClass("invisible");

        $("#DivListView").addClass("invisible");
        $("#DivListView").removeClass("visible");
        return;
    }

    function CloseDetailForm() {
        $("#DivDetailView").addClass("invisible");
        $("#DivDetailView").removeClass("visible");

        $("#DivListView").addClass("visible");
        $("#DivListView").removeClass("invisible");
        return;
    }
    </script>
}

Views/Btrade/Index.cshtml
@model IEnumerable<Broker>
@{
    ViewData["Title"] = "BrokerNames";
}

<h1>List of BrokerNames</h1>

<div class="container">
    <div class="col-12">
        <table class="table table-striped">
            <tr class="  bg-info text-black">
                @*<th>ID</th>*@
                <th>Broker Name</th>
                <th>Actions</th>
            </tr>
            @foreach(var item in Model)
            {
        <tr>
            @*<td>@item.ID</td>*@
            <td>@item.BrokerName</td>
            <td>Actions</td>
        </tr>
            }
        </table>
    </div>
</div>

Views/Btrade/RoughView.cshtml
@model BrokerTradeViewModel
@{
    ViewData["Title"] = "RoughView";
}

<h1>RoughView</h1>

<div class="col-md-4">
    <select id="ddlNationality"><option value="0">--Select Country--</option></select>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $.ajax({
            type: "POST", url: "RoughView/Btrade", dataType: "json", contentType: "application/json", success: function (res) {
                $.each(res.d, function (data, value) {

                    $("#ddlNationality").append($("<option></option>").val(value.ID).html(value.BrokerName));
                })
            }

        });

    })

</script>  

Views/Btrade/ShareCreate.cshtml
@model BrokerTradeViewModel

@{
    ViewData["Title"] = "Stocks Page";
}

<h1>ShareCreate</h1>

<form enctype="multipart/form-data" asp-controller="Btrade" asp-action="ShareCreate" method="post" class="mt-3">
<div class="bg-light border border-black col-sm-12">
    <h2 class="text-success font-weight-bold">@ViewBag.Title</h2>
    <hr />

    <div class="form-group row">
        <label asp-for="tradeinformation.brokerid" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="tradeinformation.brokerid" class="form-control" asp-items=" ViewBag.brokerlist">
                <option value="">Please select Broker</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="tradeinformation.Stockname" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="tradeinformation.Stockname" class="form-control" placeholder="Enter Name" />
            @*<span asp-validation-for="tradeinformation.Stockname" class="text-danger"></span>*@
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="tradeinformation.Stockbuykprice" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="tradeinformation.Stockbuykprice" class="form-control" placeholder="Enter Name" />
            @*<span asp-validation-for="tradeinformation.Stockbuykprice" class="text-danger"></span>*@
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="tradeinformation.Stocksellprice" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="tradeinformation.Stocksellprice" class="form-control" placeholder="Enter Stocks Sell Price" />
            @*<span asp-validation-for="tradeinformation.Stocksellprice" class="text-danger"></span>*@
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="tradeinformation.Stocktotalshares" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="tradeinformation.Stocktotalshares" class="form-control" placeholder="Enter Total Stocks" />
            @*<span asp-validation-for="tradeinformation.Stocktotalshares" class="text-danger"></span>*@
        </div>
    </div>



    <div class="form-group row">
        <label asp-for="tradeinformation.Stockpurchaseddate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input type="datetime-local" asp-for="tradeinformation.Stockpurchaseddate" class="form-control" placeholder="Enter Purchase Date" />
            @*<span asp-validation-for="tradeinformation.Stockpurchaseddate" class="text-danger"></span>*@
        </div>
    </div>


    <div class="form-group row">
        <label asp-for="tradeinformation.Stockselldate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input type="datetime-local" asp-for="tradeinformation.Stockselldate" class="form-control" placeholder="Enter Sell Date" />
            @*<span asp-validation-for="tradeinformation.Stockselldate" class="text-danger"></span>*@
        </div>
    </div>



    @*<div asp-validation-summary="All" class="text-danger" id="allvalidate"></div>*@

    <div class="form-group row">
        <div class="col-sm-10">
            <button id="btncreatesubmit" type="submit" class="btn btn-success">Add</button>
        </div>
    </div>

</div>

    </form>

Views/Btrade/ShareCreateAjax.cshtml
@model BrokerTradeViewModel

@{
    ViewData["Title"] = "Stocks Page";
}

<h1>ShareCreate</h1>

<form enctype="multipart/form-data" asp-controller="Btrade" asp-action="ShareCreate" method="post" class="mt-3">
<div class="bg-light border border-black col-sm-12">
    <h2 class="text-success font-weight-bold">@ViewBag.Title</h2>
    <hr />

    <div class="form-group row">
        <label asp-for="tradeinformation.brokerid" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <select asp-for="tradeinformation.brokerid" class="form-control" asp-items=" ViewBag.brokerlist">
                <option value="">Please select Broker</option>
            </select>
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="tradeinformation.Stockname" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="tradeinformation.Stockname" class="form-control" placeholder="Enter Name" />
            @*<span asp-validation-for="tradeinformation.Stockname" class="text-danger"></span>*@
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="tradeinformation.Stockbuykprice" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="tradeinformation.Stockbuykprice" class="form-control" placeholder="Enter Name" />
            @*<span asp-validation-for="tradeinformation.Stockbuykprice" class="text-danger"></span>*@
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="tradeinformation.Stocksellprice" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="tradeinformation.Stocksellprice" class="form-control" placeholder="Enter Stocks Sell Price" />
            @*<span asp-validation-for="tradeinformation.Stocksellprice" class="text-danger"></span>*@
        </div>
    </div>

    <div class="form-group row">
        <label asp-for="tradeinformation.Stocktotalshares" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input asp-for="tradeinformation.Stocktotalshares" class="form-control" placeholder="Enter Total Stocks" />
            @*<span asp-validation-for="tradeinformation.Stocktotalshares" class="text-danger"></span>*@
        </div>
    </div>



    <div class="form-group row">
        <label asp-for="tradeinformation.Stockpurchaseddate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input type="datetime-local" asp-for="tradeinformation.Stockpurchaseddate" class="form-control" placeholder="Enter Purchase Date" />
            @*<span asp-validation-for="tradeinformation.Stockpurchaseddate" class="text-danger"></span>*@
        </div>
    </div>


    <div class="form-group row">
        <label asp-for="tradeinformation.Stockselldate" class="col-sm-2 col-form-label"></label>
        <div class="col-sm-10">
            <input type="datetime-local" asp-for="tradeinformation.Stockselldate" class="form-control" placeholder="Enter Sell Date" />
            @*<span asp-validation-for="tradeinformation.Stockselldate" class="text-danger"></span>*@
        </div>
    </div>



    @*<div asp-validation-summary="All" class="text-danger" id="allvalidate"></div>*@

    <div class="form-group row">
        <div class="col-sm-10">
            <button id="btncreatesubmit" type="submit" class="btn btn-success">Add</button>
        </div>
    </div>

</div>

    </form>