Controllers/StockAdminController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Threading.Tasks;
using Kudvenkatcorewebapp.DBContext;
using Kudvenkatcorewebapp.Helpers;
using Kudvenkatcorewebapp.Models.Loan;
using Kudvenkatcorewebapp.Models.Trade;
using Kudvenkatcorewebapp.Repository.LoanRepository;
using Kudvenkatcorewebapp.Repository.Trade;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace Kudvenkatcorewebapp.Controllers
{
    [Authorize(Roles = "Admin")]
    public class StockAdminController : Controller
    {
        public const string V = "Data saved successfully";
       
        private readonly IProfitLoss _profitLoss;
        private readonly IConfiguration _configuration;
        private readonly AppDbContext _context;
        private readonly IBrokerRepository _brokerRepository;
        private readonly ITradeshare _tradeinformation;
        private readonly IConfiguration _configurtion;

        public StockAdminController(IProfitLoss profitLoss, IConfiguration configuration, AppDbContext context, IBrokerRepository brokerRepository, ITradeshare tradeinformation, IConfiguration configurtion)
        {
            this._profitLoss = profitLoss;
            this._configuration = configuration;
            this._context = context;
            this._brokerRepository = brokerRepository;
            this._tradeinformation = tradeinformation;
            this._configurtion = configurtion;
        }
        public IActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public IActionResult AddCustomer()
        {
            ViewBag.Name = "Add";
            Total_profit_loss profitloss = new Total_profit_loss();
            return PartialView("_InsertStockProfitLoss", profitloss);
        }

        [HttpPost]
        public async Task<IActionResult> CreateAsync(Total_profit_loss profit_Loss)
        {

            Total_profit_loss total_Profit_Losses = await _profitLoss.GetListofProfitAndLoss();

            // profit_Loss.Totalprofit = total_Profit_Losses.Totalprofit + profit_Loss.Profit;
            //profit_Loss.Totalloss = total_Profit_Losses.Totalloss + profit_Loss.Loss;

            profit_Loss.Totalprofit = GenericsLogic.Add<double>(total_Profit_Losses.Totalprofit, profit_Loss.Profit);
            profit_Loss.Totalloss = GenericsLogic.Sub<double>(total_Profit_Losses.Totalloss, profit_Loss.Loss);
            _profitLoss.AddUpdateDeleteCustomer(profit_Loss, "Insert");
            return RedirectToAction("Index");
               //  return RedirectToAction("AddCustomer");
        }
<<<<<<< HEAD

        public IActionResult AvgExtraQuantityDisplay()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddAvgExtraQuantity()
        {
            ViewBag.brokerlist = new SelectList(await _brokerRepository.GetAllBrokerListusingIenumerable(), "ID", "BrokerName");
            ViewBag.tradelist = new SelectList(await _brokerRepository.GetAllstockListusingIenumerable(), "Id", "Stockname");
            return View();
        }

        [HttpPost]
        public IActionResult AddAvgExtraQuantity(ExtraQuantityAddedinStocks extraQuantityAddedinStocks)
        {
            int i=_brokerRepository.AddExtraQuantity(extraQuantityAddedinStocks, "Insert");
            if (i > 0 || i<0)
            {
                int sngid = 1;

                ViewBag.message = sngid;
                ViewBag.Result = V;

                return View();
            }
            else
            {
                int sngid = 2;

                ViewBag.message = sngid;
            }
            return View();
        }

        //public int AddExtraQuantity(ExtraQuantityAddedinStocks extraQuantityAddedinStocks, string action)
        //{
        //    int i;
        //    //BuyrateMultyplyWithTotalSharesLogic totalintrestlogic = new BuyrateMultyplyWithTotalSharesLogic();
        //    //loanEmployees.TotalIntrest = totalintrestlogic.TotalIntrest(loanEmployees.TotalLoanAmount, loanEmployees.TotalEmi);
        //    using (SqlConnection con = new SqlConnection(_configurtion.GetConnectionString("Default")))
        //    {
        //        using (SqlCommand cmd = new SqlCommand())
        //        {
        //            try
        //            {
        //                //cmd.CommandType = CommandType.Text;
        //                cmd.Connection = con;
        //                cmd.Parameters.Clear();
        //                cmd.CommandType = CommandType.StoredProcedure;
        //                cmd.CommandText = "SP_ExtraQuantityAddedinStocks"; // Store procediure name

        //                if (action == "Insert")
        //                {
        //                   // DateTime d = Convert.ToDateTime(extraQuantityAddedinStocks.LoanDate);
        //                    //string en = loanEmployees.employeesname.ToString();

        //                    //cmd.CommandText = "INSERT INTO loanEmployees(EmployeeId,LoanID,TotalLoanAmount,TotalEmi,LoanDate,TotalIntrest,Active,LoanUserName)VALUES (@EmployeeId,@LoanID,@TotalLoanAmount,@TotalEmi,@LoanDate,@TotalIntrest,@Active,@LoanUserName)";
        //                    cmd.Parameters.AddWithValue("@brokerid", extraQuantityAddedinStocks.brokerid);
        //                    cmd.Parameters.AddWithValue("@stockid", extraQuantityAddedinStocks.stockid);
        //                    cmd.Parameters.AddWithValue("@BuyPrice", extraQuantityAddedinStocks.BuyPrice);
        //                    cmd.Parameters.AddWithValue("@TotalShare", extraQuantityAddedinStocks.TotalShare);
        //                    cmd.Parameters.AddWithValue("@TotalInvestment", extraQuantityAddedinStocks.TotalInvestment);
        //                    cmd.Parameters.AddWithValue("@Month", extraQuantityAddedinStocks.Month);
        //                    cmd.Parameters.AddWithValue("@Year", extraQuantityAddedinStocks.Year);
        //                    cmd.Parameters.AddWithValue("@Active", 1);
        //                    cmd.Parameters.AddWithValue("@action", "Insert");
        //                    // cmd.Parameters.AddWithValue("@LoanUserName", "null");
        //                }
        //                else if (action == "Update")
        //                {
        //                    //cmd.CommandText = "UPDATE Customers SET NAME = @Name,Country = @Country WHERE CustomerId = @Id";
        //                    //cmd.Parameters.AddWithValue("@Id", customer.Id);
        //                    //cmd.Parameters.AddWithValue("@Name", customer.Name);
        //                    //cmd.Parameters.AddWithValue("@Country", customer.Country);
        //                }
        //                else if (action == "Delete")
        //                {
        //                    //cmd.CommandText = "DELETE FROM Customers WHERE CustomerId = @Id";
        //                    //cmd.Parameters.AddWithValue("@Id", customer.Id);
        //                }
        //                con.Open();
        //                 i=cmd.ExecuteNonQuery();
        //                con.Close();
        //            }
        //            catch (Exception e)
        //            {
        //                throw e;
        //            }

        //            return i;
        //        }
        //    }
        //}

        //[HttpGet]
        public async Task<IActionResult> DiviidendInfoList()
        {
            //ViewBag.brokerlist = new SelectList(await _brokerRepository.GetAllBrokerListusingIenumerable(), "ID", "BrokerName");
            ViewBag.tradelist = new SelectList(await _brokerRepository.GetAllstockListusingIenumerable(), "Id", "Stockname");

            return View();

        }

        [HttpGet]
        public async Task<JsonResult> DiviidendInfoListRead()
        {
            var usages = new List<Dividend_info>();
            //var list_of_dividend_data = _context.dividend_Infos.ToList();
            var query =await (from d in _context.dividend_Infos
                                        join t in _context.tradeinformations on d.stockid equals t.Id
                                        select new
                                        {
                                            t.Stockname,
                                            d.dividendAmount,
                                            d.year,
                                            d.stockid
                                        }).ToListAsync();

            if(query?.Any() == true)
            {
                foreach (var sharesdata in query)
                {
                    usages.Add(new Dividend_info()
                    {
                        
                        stockname =sharesdata.Stockname,
                        dividendAmount = sharesdata.dividendAmount,
                         year= sharesdata.year
                    });
                }
            }
            return new  JsonResult(usages);

        }

        //Adding dividend Amount
        [HttpPost]
        public JsonResult AddDividend(Dividend_info di)
        {
            var datasave = new Dividend_info()
            {
                stockid =Convert.ToInt32( di.stockname),
                dividendAmount = di.dividendAmount,
                year = di.year
            };
            if (datasave.stockid == 0 || datasave.dividendAmount == 0.0 || datasave.year == 0)
            {
                return new JsonResult(new { success = false, message = "your request has been Not submitted" });
            }
            else
            {
                _context.dividend_Infos.AddAsync(datasave);
                _context.SaveChanges();
            }

Views/StockAdmin/AddAvgExtraQuantity.cshtml
@model BrokerTradeViewModel

@{
    ViewData["Title"] = "AddAvgExtraQuantity";
}


<div class="modal fade" id="aModal" tabindex="-1" role="dialog" aria-labelledby="aModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title" id="aModalLabel">Message</h4>
                    <button type="button" class="close" data-dismiss="aModal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    @ViewBag.Result
                </div>
                @*<div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="aModal">Close</button>
                </div>*@
            </div>
        </div>
    </div>
@{
    if (ViewBag.Result != null)
    {
        <script type="text/javascript">
            $(function () {
                $("#aModal").modal('show');
            });
        </script>
    }
}



@if (@ViewBag.message == 1)
    {
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            <strong>Good!</strong> Successfully Inserted Your Data.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    }

@if (@ViewBag.message == 2)
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <strong>Good!</strong> Error in saving Data!
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}
<hr />
<div class="row bg-light">
    <div class="col-md-4 bg-info">
        <form asp-action="AddAvgExtraQuantity" asp-controller="StockAdmin" method="post" class="mt-3">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group row">
                <label class="col-sm-6 col-form-label font-weight-bold text-black">Select-Brokers</label>
                <div class="col-sm-12">
                    <select asp-for="ExtraQuantityAddedinStocks.brokerid" class="form-control" asp-items=" ViewBag.brokerlist">
                        <option value="">Please select Broker</option>
                    </select>
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-4 col-form-label font-weight-bold text-black">Select-Stocks</label>
                <div class="col-sm-12">
                    <select asp-for="ExtraQuantityAddedinStocks.stockid" class="form-control" asp-items=" ViewBag.tradelist">
                        <option value="">Please select Stock</option>
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label font-weight-bold text-black">Buy Price</label>
                <input asp-for="ExtraQuantityAddedinStocks.BuyPrice" class="form-control" placeholder="Enter BuyPrice"/>
                <span asp-validation-for="ExtraQuantityAddedinStocks.BuyPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label font-weight-bold text-black">Total Shares</label>
                <input asp-for="ExtraQuantityAddedinStocks.TotalShare" class="form-control" />
                <span asp-validation-for="ExtraQuantityAddedinStocks.TotalShare" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label font-weight-bold text-black">Total Investment</label>
                <input asp-for="ExtraQuantityAddedinStocks.TotalInvestment" class="form-control" />
                <span asp-validation-for="ExtraQuantityAddedinStocks.TotalInvestment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label font-weight-bold text-black">Month</label>
                <input asp-for="ExtraQuantityAddedinStocks.Month" class="form-control" />
                <span asp-validation-for="ExtraQuantityAddedinStocks.Month" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label font-weight-bold text-black">Year</label>
                <input asp-for="ExtraQuantityAddedinStocks.Year" class="form-control" />
                <span asp-validation-for="ExtraQuantityAddedinStocks.Year" class="text-danger"></span>
            </div>

            <div class="form-group">

                <input type="hidden" asp-for="ExtraQuantityAddedinStocks.StockName" asp-items=" ViewBag.brokerlist" />
                <input type="hidden" asp-for="ExtraQuantityAddedinStocks.BrokerName" asp-items=" ViewBag.brokerlist" />

            </div>
            @*<div class="form-group">
            <label asp-for="Active" class="control-label"></label>
            <input asp-for="Active" class="form-control" />
            <span asp-validation-for="Active" class="text-danger"></span>
        </div>*@
            @*<div class="form-group">
            <label asp-for="brokerid" class="control-label"></label>
            <select asp-for="brokerid" class ="form-control" asp-items="ViewBag.brokerid"></select>
        </div>
        <div class="form-group">
            <label asp-for="stockid" class="control-label"></label>
            <input asp-for="stockid" class="form-control" />
            <span asp-validation-for="stockid" class="text-danger"></span>
        </div>*@
            <div class="form-group">
                <input type="submit" value="Submit" class="btn btn-primary" />
            </div>
        </form>
    </div>


</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

<link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
<script src="~/lib/bootstrap/js/bootstrap.js"></script>
<script src="~/lib/jquery/dist/jquery.js"></script>

Views/StockAdmin/DiviidendInfoList.cshtml
<<<<<<< HEAD
﻿@model Dividend_info
=======
﻿
@model Dividend_info
>>>>>>> dk
@*<div class="alert alert-warning alert-dismissible fade show" role="alert" id="sucmsg">
        <strong>Good!</strong> Successfully Inserted Your Data.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>*@

<div class="bg-gradient">
    <button type="button" id="adddividend" class="btn btn-primary m-2">Add Dividend</button>
<<<<<<< HEAD
    @*<button type="button" id='Addextrastocks' data-toggle="modal" data-target="" class="btn btn-primary m-2" onclick="Addextrastocks();">Add Extra Stock</button>*@
<button type="button" id="addextrastocks" class="btn btn-primary m-2">Add Extra Stock</button>
    <button type="button" id='Adddailyprofitloss' data-toggle="modal" data-target="" class="btn btn-primary m-2" onclick="Adddailyprofitloss();">Add Daily Income/Loss</button>
=======
    <button id='Addextrastocks' data-toggle="modal" data-target="" class="btn btn-primary m-2" onclick="Addextrastocks();">Add Extra Stock</button>
>>>>>>> dk
    @*<button type="button" id="addextrastock" class="btn btn-primary m-2"></button>*@
</div>
<table class="table table-bordered">
    <thead class="bg-primary" style="font-size:small; font-weight:bold">
        <tr>
            <th>StockName</th>
            <th>Amount</th>
            <th>Year</th>
            <th>Operations</th>
        </tr>
    </thead>
    <tbody style="font-size:small" class="text-sm-left text-muted" id="table_data">
    </tbody>
    <tfoot>
        <tr>
            <td>Total Amount :</td>
            <td id="tfoot"></td>
        </tr>
    </tfoot>
</table>


@*Boostrao Modal for dividend*@
<div class="modal fade modal" id="dividendmodal" tabindex="-1" role="dialog">
    <div class="modal-dialog" data-backdrop="static" data-keyboard="false">
        <div class="modal-content">
            <div class="modal-header bg-primary">
                <h6>Add Dividend</h6>
                <button type="button" class="close text-danger" data-dismiss="modal" aria-hidden="true" id="modalclose">
                    &times;
                </button>
            </div>

            <div class="modal-body">
                <form method="post">
                    <div class="form-group row">
                        <label class="col-sm-4 col-form-label font-weight-bold text-black">Select-Stocks</label>
                        <div class="col-sm-12">
                            <select asp-for="stockname" class="form-control" asp-items=" ViewBag.tradelist" id="stockid">
                                <option value="">Please select Stock</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="font-weight-bold">Dividend Amount</label>
                        <input type="text" class="form-control" placeholder="enter dividend" id="divamount" autocomplete="off" />
                    </div>

                    <div class="form-group">
                        <label class="font-weight-bold">Year</label>
                        <input type="text" class="form-control" id="yr" autocomplete="off" value="@DateTime.Now.Year" />
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="adddividata" onclick="AddDividend();">Add Dividend</button>
            </div>
        </div>
    </div>
</div>

@*Boostrao Modal for Extra Stocks*@
<!--<div id="showmodal" class="modal fade">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
           
        </div>--><!-- /.modal-content -->
    <!--</div>--><!-- /.modal-dialog -->
<!--</div>--><!-- /.modal -->

<<<<<<< HEAD
@*Add Extra Stock Logic*@
=======

>>>>>>> dk
<div class="modal fade" id="mymodal1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title bg-light">Add Extra Stock</h3>
                <button type="button" class="close text-danger" data-dismiss="modal" aria-hidden="true" id="extrastockmodalclose"> &times;</button>

            </div>

            <div class="modal-body" id="myModalBodyDiv1">

            </div>

            @*<div class="modal-footer">
                <a href="#"  class="btn btn-primary">Save changes</a>
                <a href="#"  class="btn btn-secondary" data-dismiss="modal">Close</a>
            </div>*@
        </div>
    </div>
</div>

<<<<<<< HEAD
@*Add Daily Profit and Loss*@
<div class="modal fade" id="mymodal2">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title text-black font-weight-bold">Add Daily Profit and Loss</h3>
                <button type="button" class="close text-danger" data-dismiss="modal" aria-hidden="true" id="CloseDailyProfitLoss"> &times;</button>

            </div>

            <div class="modal-body" id="myModalBodyDiv2">

            </div>

            @*<div class="modal-footer">
                    <a href="#"  class="btn btn-primary">Save changes</a>
                    <a href="#"  class="btn btn-secondary" data-dismiss="modal">Close</a>
                </div>*@
        </div>
    </div>
</div>

=======
>>>>>>> dk

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/js/bootstrap.min.js"></script>
<script src="~/js/CustomScript.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.js"></script>
<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.4/toastr.min.css" rel="stylesheet">

Views/StockAdmin/Index.cshtml
@model Kudvenkatcorewebapp.ViewModels.Trade.AdminStockViewModel
@{
    ViewData["Title"] = "Index";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />


<script type="text/javascript">
    $(document).ready(function () {

        $("body").on('click', '#btnAddsave', function () {
            //$("#MyPopup").modal("hide");
            $.ajax({
                url: 'StockAdmin/AddCustomer',
                data: {},
                type: 'POST',
                dataType: 'html',
                contentType: "application/json; charset=utf-8",
                success: function (response) {
                    $("#dvPartial").html(response);
                    $("#MyPopup").modal("show");
                }
            });
        });
    });


</script>


<p>
    <button id="btnAddsave" type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
        Add Loan Details
    </button>
</p>

<div class="modal fade" data-keyboard="false" data-backdrop="static" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Profit And Loss</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <div id="dvPartial"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                @*<button id="btnAddsavedatabase" type="button" class="btn btn-primary">Save changes</button>*@
            </div>
        </div>
    </div>
</div>

Views/StockAdmin/_dividendModalPartial.cshtml
@model Dividend_info

<div class="modal fade" id="addDividend">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title" id="addEmployeeLabel">Add dividend</h4>
                <button type="button" class="close" data-dismiss="modal">
                    <span>X</span>
                </button>
            </div>

            <div class="modal-body">
                <form action="Create">
                    <div class="form-group">
                        <label>Select Stock</label>
                        <input asp-for="stockid" class="form-control" />
                        <span asp-validation-for="stockid" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Dividend Amountk</label>
                        <input asp-for="dividendAmount" class="form-control" />
                        <span asp-validation-for="dividendAmount" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label>Year</label>
                        <input asp-for="year" class="form-control" />
                        <span asp-validation-for="year" class="text-danger"></span>
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">close</button>
                <button type="button" class="btn btn-danger" data-save="modal">Save</button>
            </div>

        </div>
    </div>
</div>

Views/StockAdmin/_showParticalView.cshtml
@model BrokerTradeViewModel
@*
    For more information on enabling Kudvenkatcorewebapp.Models.Trade for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@




    <div class="row bg-light">
        <div class="col-md-12 bg-info">
            
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                <div class="form-group row">
                    <label class="col-sm-6 col-form-label font-weight-bold text-black">Select-Brokers</label>
                    <div class="col-sm-12">
                        <select asp-for="ExtraQuantityAddedinStocks.brokerid" class="form-control" asp-items=" ViewBag.brokerlist" id="brokerid">
                            <option value="">Please select Broker</option>
                        </select>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-4 col-form-label font-weight-bold text-black">Select-Stocks</label>
                    <div class="col-sm-12">
                        <select asp-for="ExtraQuantityAddedinStocks.stockid" class="form-control" asp-items=" ViewBag.tradelist" id="id">
                            <option value="">Please select Stock</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="control-label font-weight-bold text-black">Buy Price</label>
                    <input asp-for="ExtraQuantityAddedinStocks.BuyPrice" class="form-control" autocomplete="off" placeholder="Enter BuyPrice" id="buyprice" />
                    <span asp-validation-for="ExtraQuantityAddedinStocks.BuyPrice" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label font-weight-bold text-black">Total Shares</label>
                    <input asp-for="ExtraQuantityAddedinStocks.TotalShare" class="form-control" id="totalshare" />
                    <span asp-validation-for="ExtraQuantityAddedinStocks.TotalShare" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label font-weight-bold text-black">Total Investment</label>
                    <input asp-for="ExtraQuantityAddedinStocks.TotalInvestment" class="form-control" id="totalinvestment" />
                    <span asp-validation-for="ExtraQuantityAddedinStocks.TotalInvestment" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label font-weight-bold text-black">Month</label>
                    <input asp-for="ExtraQuantityAddedinStocks.Month" class="form-control" id="month" />
                    <span asp-validation-for="ExtraQuantityAddedinStocks.Month" class="text-danger"></span>
                </div>

                <div class="form-group">
                    <label class="control-label font-weight-bold text-black">Year</label>
                    <input asp-for="ExtraQuantityAddedinStocks.Year" class="form-control" id="year"/>
                    <span asp-validation-for="ExtraQuantityAddedinStocks.Year" class="text-danger"></span>
                </div>

                <div class="form-group">

                    <input type="hidden" asp-for="ExtraQuantityAddedinStocks.StockName" asp-items=" ViewBag.brokerlist" />
                    <input type="hidden" asp-for="ExtraQuantityAddedinStocks.BrokerName" asp-items=" ViewBag.brokerlist" />

                </div>

                <div class="form-group">
                    <input type="submit" value="Submit" class="btn btn-primary" id="btnsubmit" onclick="Addextrastock();" />
                </div>
          
        </div>
    </div>